package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Discrete_Solution <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface Discrete_Solution extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isDiscreteSolutionOf
     */
     
    /**
     * Gets all property values for the isDiscreteSolutionOf property.<p>
     * 
     * @returns a collection of values for the isDiscreteSolutionOf property.
     */
    Collection<? extends Discrete_Model> getIsDiscreteSolutionOf();

    /**
     * Checks if the class has a isDiscreteSolutionOf property value.<p>
     * 
     * @return true if there is a isDiscreteSolutionOf property value.
     */
    boolean hasIsDiscreteSolutionOf();

    /**
     * Adds a isDiscreteSolutionOf property value.<p>
     * 
     * @param newIsDiscreteSolutionOf the isDiscreteSolutionOf property value to be added
     */
    void addIsDiscreteSolutionOf(Discrete_Model newIsDiscreteSolutionOf);

    /**
     * Removes a isDiscreteSolutionOf property value.<p>
     * 
     * @param oldIsDiscreteSolutionOf the isDiscreteSolutionOf property value to be removed.
     */
    void removeIsDiscreteSolutionOf(Discrete_Model oldIsDiscreteSolutionOf);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isSimulatedBy
     */
     
    /**
     * Gets all property values for the isSimulatedBy property.<p>
     * 
     * @returns a collection of values for the isSimulatedBy property.
     */
    Collection<? extends WrappedIndividual> getIsSimulatedBy();

    /**
     * Checks if the class has a isSimulatedBy property value.<p>
     * 
     * @return true if there is a isSimulatedBy property value.
     */
    boolean hasIsSimulatedBy();

    /**
     * Adds a isSimulatedBy property value.<p>
     * 
     * @param newIsSimulatedBy the isSimulatedBy property value to be added
     */
    void addIsSimulatedBy(WrappedIndividual newIsSimulatedBy);

    /**
     * Removes a isSimulatedBy property value.<p>
     * 
     * @param oldIsSimulatedBy the isSimulatedBy property value to be removed.
     */
    void removeIsSimulatedBy(WrappedIndividual oldIsSimulatedBy);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
