package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: DomainSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */

public interface DomainSettings extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areDomainSettingsOf
     */
     
    /**
     * Gets all property values for the areDomainSettingsOf property.<p>
     * 
     * @returns a collection of values for the areDomainSettingsOf property.
     */
    Collection<? extends Finite_Element_Model_Domain> getAreDomainSettingsOf();

    /**
     * Checks if the class has a areDomainSettingsOf property value.<p>
     * 
     * @return true if there is a areDomainSettingsOf property value.
     */
    boolean hasAreDomainSettingsOf();

    /**
     * Adds a areDomainSettingsOf property value.<p>
     * 
     * @param newAreDomainSettingsOf the areDomainSettingsOf property value to be added
     */
    void addAreDomainSettingsOf(Finite_Element_Model_Domain newAreDomainSettingsOf);

    /**
     * Removes a areDomainSettingsOf property value.<p>
     * 
     * @param oldAreDomainSettingsOf the areDomainSettingsOf property value to be removed.
     */
    void removeAreDomainSettingsOf(Finite_Element_Model_Domain oldAreDomainSettingsOf);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
