package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Elemenmt_Group <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface Elemenmt_Group extends Subdomain_group {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasElementGroupSetting
     */
     
    /**
     * Gets all property values for the hasElementGroupSetting property.<p>
     * 
     * @returns a collection of values for the hasElementGroupSetting property.
     */
    Collection<? extends ElementGroupSettings> getHasElementGroupSetting();

    /**
     * Checks if the class has a hasElementGroupSetting property value.<p>
     * 
     * @return true if there is a hasElementGroupSetting property value.
     */
    boolean hasHasElementGroupSetting();

    /**
     * Adds a hasElementGroupSetting property value.<p>
     * 
     * @param newHasElementGroupSetting the hasElementGroupSetting property value to be added
     */
    void addHasElementGroupSetting(ElementGroupSettings newHasElementGroupSetting);

    /**
     * Removes a hasElementGroupSetting property value.<p>
     * 
     * @param oldHasElementGroupSetting the hasElementGroupSetting property value to be removed.
     */
    void removeHasElementGroupSetting(ElementGroupSettings oldHasElementGroupSetting);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasMaterial
     */
     
    /**
     * Gets all property values for the hasMaterial property.<p>
     * 
     * @returns a collection of values for the hasMaterial property.
     */
    Collection<? extends Material> getHasMaterial();

    /**
     * Checks if the class has a hasMaterial property value.<p>
     * 
     * @return true if there is a hasMaterial property value.
     */
    boolean hasHasMaterial();

    /**
     * Adds a hasMaterial property value.<p>
     * 
     * @param newHasMaterial the hasMaterial property value to be added
     */
    void addHasMaterial(Material newHasMaterial);

    /**
     * Removes a hasMaterial property value.<p>
     * 
     * @param oldHasMaterial the hasMaterial property value to be removed.
     */
    void removeHasMaterial(Material oldHasMaterial);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasVertex
     */
     
    /**
     * Gets all property values for the hasVertex property.<p>
     * 
     * @returns a collection of values for the hasVertex property.
     */
    Collection<? extends Node> getHasVertex();

    /**
     * Checks if the class has a hasVertex property value.<p>
     * 
     * @return true if there is a hasVertex property value.
     */
    boolean hasHasVertex();

    /**
     * Adds a hasVertex property value.<p>
     * 
     * @param newHasVertex the hasVertex property value to be added
     */
    void addHasVertex(Node newHasVertex);

    /**
     * Removes a hasVertex property value.<p>
     * 
     * @param oldHasVertex the hasVertex property value to be removed.
     */
    void removeHasVertex(Node oldHasVertex);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasSpatialDimension
     */
     
    /**
     * Gets all property values for the hasSpatialDimension property.<p>
     * 
     * @returns a collection of values for the hasSpatialDimension property.
     */
    Collection<? extends Integer> getHasSpatialDimension();

    /**
     * Checks if the class has a hasSpatialDimension property value.<p>
     * 
     * @return true if there is a hasSpatialDimension property value.
     */
    boolean hasHasSpatialDimension();

    /**
     * Adds a hasSpatialDimension property value.<p>
     * 
     * @param newHasSpatialDimension the hasSpatialDimension property value to be added
     */
    void addHasSpatialDimension(Integer newHasSpatialDimension);

    /**
     * Removes a hasSpatialDimension property value.<p>
     * 
     * @param oldHasSpatialDimension the hasSpatialDimension property value to be removed.
     */
    void removeHasSpatialDimension(Integer oldHasSpatialDimension);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
