package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: ElementGroupSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */

public interface ElementGroupSettings extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areElementGroupSettingsOf
     */
     
    /**
     * Gets all property values for the areElementGroupSettingsOf property.<p>
     * 
     * @returns a collection of values for the areElementGroupSettingsOf property.
     */
    Collection<? extends Elemenmt_Group> getAreElementGroupSettingsOf();

    /**
     * Checks if the class has a areElementGroupSettingsOf property value.<p>
     * 
     * @return true if there is a areElementGroupSettingsOf property value.
     */
    boolean hasAreElementGroupSettingsOf();

    /**
     * Adds a areElementGroupSettingsOf property value.<p>
     * 
     * @param newAreElementGroupSettingsOf the areElementGroupSettingsOf property value to be added
     */
    void addAreElementGroupSettingsOf(Elemenmt_Group newAreElementGroupSettingsOf);

    /**
     * Removes a areElementGroupSettingsOf property value.<p>
     * 
     * @param oldAreElementGroupSettingsOf the areElementGroupSettingsOf property value to be removed.
     */
    void removeAreElementGroupSettingsOf(Elemenmt_Group oldAreElementGroupSettingsOf);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#IATYP
     */
     
    /**
     * Gets all property values for the IATYP property.<p>
     * 
     * @returns a collection of values for the IATYP property.
     */
    Collection<? extends Integer> getIATYP();

    /**
     * Checks if the class has a IATYP property value.<p>
     * 
     * @return true if there is a IATYP property value.
     */
    boolean hasIATYP();

    /**
     * Adds a IATYP property value.<p>
     * 
     * @param newIATYP the IATYP property value to be added
     */
    void addIATYP(Integer newIATYP);

    /**
     * Removes a IATYP property value.<p>
     * 
     * @param oldIATYP the IATYP property value to be removed.
     */
    void removeIATYP(Integer oldIATYP);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#INDAX
     */
     
    /**
     * Gets all property values for the INDAX property.<p>
     * 
     * @returns a collection of values for the INDAX property.
     */
    Collection<? extends Integer> getINDAX();

    /**
     * Checks if the class has a INDAX property value.<p>
     * 
     * @return true if there is a INDAX property value.
     */
    boolean hasINDAX();

    /**
     * Adds a INDAX property value.<p>
     * 
     * @param newINDAX the INDAX property value to be added
     */
    void addINDAX(Integer newINDAX);

    /**
     * Removes a INDAX property value.<p>
     * 
     * @param oldINDAX the INDAX property value to be removed.
     */
    void removeINDAX(Integer oldINDAX);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#IPN
     */
     
    /**
     * Gets all property values for the IPN property.<p>
     * 
     * @returns a collection of values for the IPN property.
     */
    Collection<? extends Integer> getIPN();

    /**
     * Checks if the class has a IPN property value.<p>
     * 
     * @return true if there is a IPN property value.
     */
    boolean hasIPN();

    /**
     * Adds a IPN property value.<p>
     * 
     * @param newIPN the IPN property value to be added
     */
    void addIPN(Integer newIPN);

    /**
     * Removes a IPN property value.<p>
     * 
     * @param oldIPN the IPN property value to be removed.
     */
    void removeIPN(Integer oldIPN);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#NMODM
     */
     
    /**
     * Gets all property values for the NMODM property.<p>
     * 
     * @returns a collection of values for the NMODM property.
     */
    Collection<? extends Integer> getNMODM();

    /**
     * Checks if the class has a NMODM property value.<p>
     * 
     * @return true if there is a NMODM property value.
     */
    boolean hasNMODM();

    /**
     * Adds a NMODM property value.<p>
     * 
     * @param newNMODM the NMODM property value to be added
     */
    void addNMODM(Integer newNMODM);

    /**
     * Removes a NMODM property value.<p>
     * 
     * @param oldNMODM the NMODM property value to be removed.
     */
    void removeNMODM(Integer oldNMODM);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
