package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Equation <br>
 * @version generated on Mon May 11 16:25:18 BST 2015 by jbjares
 */

public interface Equation extends WrappedIndividual {

    /* ***************************************************
     * Property http://codata.jp/OML-Property.owl#Eq
     */
     
    /**
     * Gets all property values for the Eq property.<p>
     * 
     * @returns a collection of values for the Eq property.
     */
    Collection<? extends Object> getEq();

    /**
     * Checks if the class has a Eq property value.<p>
     * 
     * @return true if there is a Eq property value.
     */
    boolean hasEq();

    /**
     * Adds a Eq property value.<p>
     * 
     * @param newEq the Eq property value to be added
     */
    void addEq(Object newEq);

    /**
     * Removes a Eq property value.<p>
     * 
     * @param oldEq the Eq property value to be removed.
     */
    void removeEq(Object oldEq);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
