package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: FiniteElementModelSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */

public interface FiniteElementModelSettings extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areFiniteElementModelSettingsOf
     */
     
    /**
     * Gets all property values for the areFiniteElementModelSettingsOf property.<p>
     * 
     * @returns a collection of values for the areFiniteElementModelSettingsOf property.
     */
    Collection<? extends Finite_Element_Model> getAreFiniteElementModelSettingsOf();

    /**
     * Checks if the class has a areFiniteElementModelSettingsOf property value.<p>
     * 
     * @return true if there is a areFiniteElementModelSettingsOf property value.
     */
    boolean hasAreFiniteElementModelSettingsOf();

    /**
     * Adds a areFiniteElementModelSettingsOf property value.<p>
     * 
     * @param newAreFiniteElementModelSettingsOf the areFiniteElementModelSettingsOf property value to be added
     */
    void addAreFiniteElementModelSettingsOf(Finite_Element_Model newAreFiniteElementModelSettingsOf);

    /**
     * Removes a areFiniteElementModelSettingsOf property value.<p>
     * 
     * @param oldAreFiniteElementModelSettingsOf the areFiniteElementModelSettingsOf property value to be removed.
     */
    void removeAreFiniteElementModelSettingsOf(Finite_Element_Model oldAreFiniteElementModelSettingsOf);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#INDFOR
     */
     
    /**
     * Gets all property values for the INDFOR property.<p>
     * 
     * @returns a collection of values for the INDFOR property.
     */
    Collection<? extends Integer> getINDFOR();

    /**
     * Checks if the class has a INDFOR property value.<p>
     * 
     * @return true if there is a INDFOR property value.
     */
    boolean hasINDFOR();

    /**
     * Adds a INDFOR property value.<p>
     * 
     * @param newINDFOR the INDFOR property value to be added
     */
    void addINDFOR(Integer newINDFOR);

    /**
     * Removes a INDFOR property value.<p>
     * 
     * @param oldINDFOR the INDFOR property value to be removed.
     */
    void removeINDFOR(Integer oldINDFOR);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasHeading
     */
     
    /**
     * Gets all property values for the hasHeading property.<p>
     * 
     * @returns a collection of values for the hasHeading property.
     */
    Collection<? extends String> getHasHeading();

    /**
     * Checks if the class has a hasHeading property value.<p>
     * 
     * @return true if there is a hasHeading property value.
     */
    boolean hasHasHeading();

    /**
     * Adds a hasHeading property value.<p>
     * 
     * @param newHasHeading the hasHeading property value to be added
     */
    void addHasHeading(String newHasHeading);

    /**
     * Removes a hasHeading property value.<p>
     * 
     * @param oldHasHeading the hasHeading property value to be removed.
     */
    void removeHasHeading(String oldHasHeading);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
