package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Initial_Condition <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface Initial_Condition extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isInitialConditionOf
     */
     
    /**
     * Gets all property values for the isInitialConditionOf property.<p>
     * 
     * @returns a collection of values for the isInitialConditionOf property.
     */
    Collection<? extends Solver> getIsInitialConditionOf();

    /**
     * Checks if the class has a isInitialConditionOf property value.<p>
     * 
     * @return true if there is a isInitialConditionOf property value.
     */
    boolean hasIsInitialConditionOf();

    /**
     * Adds a isInitialConditionOf property value.<p>
     * 
     * @param newIsInitialConditionOf the isInitialConditionOf property value to be added
     */
    void addIsInitialConditionOf(Solver newIsInitialConditionOf);

    /**
     * Removes a isInitialConditionOf property value.<p>
     * 
     * @param oldIsInitialConditionOf the isInitialConditionOf property value to be removed.
     */
    void removeIsInitialConditionOf(Solver oldIsInitialConditionOf);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
