package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Inner_Ear <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface Inner_Ear extends Physical_System {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isIdealizedBy
     */
     
    /**
     * Gets all property values for the isIdealizedBy property.<p>
     * 
     * @returns a collection of values for the isIdealizedBy property.
     */
    Collection<? extends Mathematical_Model> getIsIdealizedBy();

    /**
     * Checks if the class has a isIdealizedBy property value.<p>
     * 
     * @return true if there is a isIdealizedBy property value.
     */
    boolean hasIsIdealizedBy();

    /**
     * Adds a isIdealizedBy property value.<p>
     * 
     * @param newIsIdealizedBy the isIdealizedBy property value to be added
     */
    void addIsIdealizedBy(Mathematical_Model newIsIdealizedBy);

    /**
     * Removes a isIdealizedBy property value.<p>
     * 
     * @param oldIsIdealizedBy the isIdealizedBy property value to be removed.
     */
    void removeIsIdealizedBy(Mathematical_Model oldIsIdealizedBy);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
