package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Loading_ <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface Loading_ extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isLoadOf
     */
     
    /**
     * Gets all property values for the isLoadOf property.<p>
     * 
     * @returns a collection of values for the isLoadOf property.
     */
    Collection<? extends Finite_Element_Model_Domain> getIsLoadOf();

    /**
     * Checks if the class has a isLoadOf property value.<p>
     * 
     * @return true if there is a isLoadOf property value.
     */
    boolean hasIsLoadOf();

    /**
     * Adds a isLoadOf property value.<p>
     * 
     * @param newIsLoadOf the isLoadOf property value to be added
     */
    void addIsLoadOf(Finite_Element_Model_Domain newIsLoadOf);

    /**
     * Removes a isLoadOf property value.<p>
     * 
     * @param oldIsLoadOf the isLoadOf property value to be removed.
     */
    void removeIsLoadOf(Finite_Element_Model_Domain oldIsLoadOf);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasNumberOfForces
     */
     
    /**
     * Gets all property values for the hasNumberOfForces property.<p>
     * 
     * @returns a collection of values for the hasNumberOfForces property.
     */
    Collection<? extends Integer> getHasNumberOfForces();

    /**
     * Checks if the class has a hasNumberOfForces property value.<p>
     * 
     * @return true if there is a hasNumberOfForces property value.
     */
    boolean hasHasNumberOfForces();

    /**
     * Adds a hasNumberOfForces property value.<p>
     * 
     * @param newHasNumberOfForces the hasNumberOfForces property value to be added
     */
    void addHasNumberOfForces(Integer newHasNumberOfForces);

    /**
     * Removes a hasNumberOfForces property value.<p>
     * 
     * @param oldHasNumberOfForces the hasNumberOfForces property value to be removed.
     */
    void removeHasNumberOfForces(Integer oldHasNumberOfForces);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
