package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Material_Property <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface Material_Property extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isMaterialPropertyOf
     */
     
    /**
     * Gets all property values for the isMaterialPropertyOf property.<p>
     * 
     * @returns a collection of values for the isMaterialPropertyOf property.
     */
    Collection<? extends WrappedIndividual> getIsMaterialPropertyOf();

    /**
     * Checks if the class has a isMaterialPropertyOf property value.<p>
     * 
     * @return true if there is a isMaterialPropertyOf property value.
     */
    boolean hasIsMaterialPropertyOf();

    /**
     * Adds a isMaterialPropertyOf property value.<p>
     * 
     * @param newIsMaterialPropertyOf the isMaterialPropertyOf property value to be added
     */
    void addIsMaterialPropertyOf(WrappedIndividual newIsMaterialPropertyOf);

    /**
     * Removes a isMaterialPropertyOf property value.<p>
     * 
     * @param oldIsMaterialPropertyOf the isMaterialPropertyOf property value to be removed.
     */
    void removeIsMaterialPropertyOf(WrappedIndividual oldIsMaterialPropertyOf);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isMaterialPropertyUsedBy
     */
     
    /**
     * Gets all property values for the isMaterialPropertyUsedBy property.<p>
     * 
     * @returns a collection of values for the isMaterialPropertyUsedBy property.
     */
    Collection<? extends Solver> getIsMaterialPropertyUsedBy();

    /**
     * Checks if the class has a isMaterialPropertyUsedBy property value.<p>
     * 
     * @return true if there is a isMaterialPropertyUsedBy property value.
     */
    boolean hasIsMaterialPropertyUsedBy();

    /**
     * Adds a isMaterialPropertyUsedBy property value.<p>
     * 
     * @param newIsMaterialPropertyUsedBy the isMaterialPropertyUsedBy property value to be added
     */
    void addIsMaterialPropertyUsedBy(Solver newIsMaterialPropertyUsedBy);

    /**
     * Removes a isMaterialPropertyUsedBy property value.<p>
     * 
     * @param oldIsMaterialPropertyUsedBy the isMaterialPropertyUsedBy property value to be removed.
     */
    void removeIsMaterialPropertyUsedBy(Solver oldIsMaterialPropertyUsedBy);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasMaterialPropertyValue
     */
     
    /**
     * Gets all property values for the hasMaterialPropertyValue property.<p>
     * 
     * @returns a collection of values for the hasMaterialPropertyValue property.
     */
    Collection<? extends Object> getHasMaterialPropertyValue();

    /**
     * Checks if the class has a hasMaterialPropertyValue property value.<p>
     * 
     * @return true if there is a hasMaterialPropertyValue property value.
     */
    boolean hasHasMaterialPropertyValue();

    /**
     * Adds a hasMaterialPropertyValue property value.<p>
     * 
     * @param newHasMaterialPropertyValue the hasMaterialPropertyValue property value to be added
     */
    void addHasMaterialPropertyValue(Object newHasMaterialPropertyValue);

    /**
     * Removes a hasMaterialPropertyValue property value.<p>
     * 
     * @param oldHasMaterialPropertyValue the hasMaterialPropertyValue property value to be removed.
     */
    void removeHasMaterialPropertyValue(Object oldHasMaterialPropertyValue);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
