package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: MatrixValue <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface MatrixValue extends Value {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasInputStatus
     */
     
    /**
     * Gets all property values for the hasInputStatus property.<p>
     * 
     * @returns a collection of values for the hasInputStatus property.
     */
    Collection<? extends Object> getHasInputStatus();

    /**
     * Checks if the class has a hasInputStatus property value.<p>
     * 
     * @return true if there is a hasInputStatus property value.
     */
    boolean hasHasInputStatus();

    /**
     * Adds a hasInputStatus property value.<p>
     * 
     * @param newHasInputStatus the hasInputStatus property value to be added
     */
    void addHasInputStatus(Object newHasInputStatus);

    /**
     * Removes a hasInputStatus property value.<p>
     * 
     * @param oldHasInputStatus the hasInputStatus property value to be removed.
     */
    void removeHasInputStatus(Object oldHasInputStatus);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasMatrixDataValue
     */
     
    /**
     * Gets all property values for the hasMatrixDataValue property.<p>
     * 
     * @returns a collection of values for the hasMatrixDataValue property.
     */
    Collection<? extends Object> getHasMatrixDataValue();

    /**
     * Checks if the class has a hasMatrixDataValue property value.<p>
     * 
     * @return true if there is a hasMatrixDataValue property value.
     */
    boolean hasHasMatrixDataValue();

    /**
     * Adds a hasMatrixDataValue property value.<p>
     * 
     * @param newHasMatrixDataValue the hasMatrixDataValue property value to be added
     */
    void addHasMatrixDataValue(Object newHasMatrixDataValue);

    /**
     * Removes a hasMatrixDataValue property value.<p>
     * 
     * @param oldHasMatrixDataValue the hasMatrixDataValue property value to be removed.
     */
    void removeHasMatrixDataValue(Object oldHasMatrixDataValue);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
