package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: MeshSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */

public interface MeshSettings extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areMeshSettingsOf
     */
     
    /**
     * Gets all property values for the areMeshSettingsOf property.<p>
     * 
     * @returns a collection of values for the areMeshSettingsOf property.
     */
    Collection<? extends Mesh> getAreMeshSettingsOf();

    /**
     * Checks if the class has a areMeshSettingsOf property value.<p>
     * 
     * @return true if there is a areMeshSettingsOf property value.
     */
    boolean hasAreMeshSettingsOf();

    /**
     * Adds a areMeshSettingsOf property value.<p>
     * 
     * @param newAreMeshSettingsOf the areMeshSettingsOf property value to be added
     */
    void addAreMeshSettingsOf(Mesh newAreMeshSettingsOf);

    /**
     * Removes a areMeshSettingsOf property value.<p>
     * 
     * @param oldAreMeshSettingsOf the areMeshSettingsOf property value to be removed.
     */
    void removeAreMeshSettingsOf(Mesh oldAreMeshSettingsOf);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#ISWELL
     */
     
    /**
     * Gets all property values for the ISWELL property.<p>
     * 
     * @returns a collection of values for the ISWELL property.
     */
    Collection<? extends Integer> getISWELL();

    /**
     * Checks if the class has a ISWELL property value.<p>
     * 
     * @return true if there is a ISWELL property value.
     */
    boolean hasISWELL();

    /**
     * Adds a ISWELL property value.<p>
     * 
     * @param newISWELL the ISWELL property value to be added
     */
    void addISWELL(Integer newISWELL);

    /**
     * Removes a ISWELL property value.<p>
     * 
     * @param oldISWELL the ISWELL property value to be removed.
     */
    void removeISWELL(Integer oldISWELL);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#NUMZAD
     */
     
    /**
     * Gets all property values for the NUMZAD property.<p>
     * 
     * @returns a collection of values for the NUMZAD property.
     */
    Collection<? extends Object> getNUMZAD();

    /**
     * Checks if the class has a NUMZAD property value.<p>
     * 
     * @return true if there is a NUMZAD property value.
     */
    boolean hasNUMZAD();

    /**
     * Adds a NUMZAD property value.<p>
     * 
     * @param newNUMZAD the NUMZAD property value to be added
     */
    void addNUMZAD(Object newNUMZAD);

    /**
     * Removes a NUMZAD property value.<p>
     * 
     * @param oldNUMZAD the NUMZAD property value to be removed.
     */
    void removeNUMZAD(Object oldNUMZAD);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
