package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: ScalarValue <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface ScalarValue extends Value {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasInputStatus
     */
     
    /**
     * Gets all property values for the hasInputStatus property.<p>
     * 
     * @returns a collection of values for the hasInputStatus property.
     */
    Collection<? extends Object> getHasInputStatus();

    /**
     * Checks if the class has a hasInputStatus property value.<p>
     * 
     * @return true if there is a hasInputStatus property value.
     */
    boolean hasHasInputStatus();

    /**
     * Adds a hasInputStatus property value.<p>
     * 
     * @param newHasInputStatus the hasInputStatus property value to be added
     */
    void addHasInputStatus(Object newHasInputStatus);

    /**
     * Removes a hasInputStatus property value.<p>
     * 
     * @param oldHasInputStatus the hasInputStatus property value to be removed.
     */
    void removeHasInputStatus(Object oldHasInputStatus);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasScalarDataValue
     */
     
    /**
     * Gets all property values for the hasScalarDataValue property.<p>
     * 
     * @returns a collection of values for the hasScalarDataValue property.
     */
    Collection<? extends Object> getHasScalarDataValue();

    /**
     * Checks if the class has a hasScalarDataValue property value.<p>
     * 
     * @return true if there is a hasScalarDataValue property value.
     */
    boolean hasHasScalarDataValue();

    /**
     * Adds a hasScalarDataValue property value.<p>
     * 
     * @param newHasScalarDataValue the hasScalarDataValue property value to be added
     */
    void addHasScalarDataValue(Object newHasScalarDataValue);

    /**
     * Removes a hasScalarDataValue property value.<p>
     * 
     * @param oldHasScalarDataValue the hasScalarDataValue property value to be removed.
     */
    void removeHasScalarDataValue(Object oldHasScalarDataValue);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
