package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: SolverSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */

public interface SolverSettings extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areSolverSettingsOf
     */
     
    /**
     * Gets all property values for the areSolverSettingsOf property.<p>
     * 
     * @returns a collection of values for the areSolverSettingsOf property.
     */
    Collection<? extends Solver> getAreSolverSettingsOf();

    /**
     * Checks if the class has a areSolverSettingsOf property value.<p>
     * 
     * @return true if there is a areSolverSettingsOf property value.
     */
    boolean hasAreSolverSettingsOf();

    /**
     * Adds a areSolverSettingsOf property value.<p>
     * 
     * @param newAreSolverSettingsOf the areSolverSettingsOf property value to be added
     */
    void addAreSolverSettingsOf(Solver newAreSolverSettingsOf);

    /**
     * Removes a areSolverSettingsOf property value.<p>
     * 
     * @param oldAreSolverSettingsOf the areSolverSettingsOf property value to be removed.
     */
    void removeAreSolverSettingsOf(Solver oldAreSolverSettingsOf);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#EPSTA
     */
     
    /**
     * Gets all property values for the EPSTA property.<p>
     * 
     * @returns a collection of values for the EPSTA property.
     */
    Collection<? extends Object> getEPSTA();

    /**
     * Checks if the class has a EPSTA property value.<p>
     * 
     * @return true if there is a EPSTA property value.
     */
    boolean hasEPSTA();

    /**
     * Adds a EPSTA property value.<p>
     * 
     * @param newEPSTA the EPSTA property value to be added
     */
    void addEPSTA(Object newEPSTA);

    /**
     * Removes a EPSTA property value.<p>
     * 
     * @param oldEPSTA the EPSTA property value to be removed.
     */
    void removeEPSTA(Object oldEPSTA);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#EPSTR
     */
     
    /**
     * Gets all property values for the EPSTR property.<p>
     * 
     * @returns a collection of values for the EPSTR property.
     */
    Collection<? extends Object> getEPSTR();

    /**
     * Checks if the class has a EPSTR property value.<p>
     * 
     * @return true if there is a EPSTR property value.
     */
    boolean hasEPSTR();

    /**
     * Adds a EPSTR property value.<p>
     * 
     * @param newEPSTR the EPSTR property value to be added
     */
    void addEPSTR(Object newEPSTR);

    /**
     * Removes a EPSTR property value.<p>
     * 
     * @param oldEPSTR the EPSTR property value to be removed.
     */
    void removeEPSTR(Object oldEPSTR);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#IBR
     */
     
    /**
     * Gets all property values for the IBR property.<p>
     * 
     * @returns a collection of values for the IBR property.
     */
    Collection<? extends Integer> getIBR();

    /**
     * Checks if the class has a IBR property value.<p>
     * 
     * @return true if there is a IBR property value.
     */
    boolean hasIBR();

    /**
     * Adds a IBR property value.<p>
     * 
     * @param newIBR the IBR property value to be added
     */
    void addIBR(Integer newIBR);

    /**
     * Removes a IBR property value.<p>
     * 
     * @param oldIBR the IBR property value to be removed.
     */
    void removeIBR(Integer oldIBR);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#IFORM
     */
     
    /**
     * Gets all property values for the IFORM property.<p>
     * 
     * @returns a collection of values for the IFORM property.
     */
    Collection<? extends Integer> getIFORM();

    /**
     * Checks if the class has a IFORM property value.<p>
     * 
     * @return true if there is a IFORM property value.
     */
    boolean hasIFORM();

    /**
     * Adds a IFORM property value.<p>
     * 
     * @param newIFORM the IFORM property value to be added
     */
    void addIFORM(Integer newIFORM);

    /**
     * Removes a IFORM property value.<p>
     * 
     * @param oldIFORM the IFORM property value to be removed.
     */
    void removeIFORM(Integer oldIFORM);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#IMAX
     */
     
    /**
     * Gets all property values for the IMAX property.<p>
     * 
     * @returns a collection of values for the IMAX property.
     */
    Collection<? extends Integer> getIMAX();

    /**
     * Checks if the class has a IMAX property value.<p>
     * 
     * @return true if there is a IMAX property value.
     */
    boolean hasIMAX();

    /**
     * Adds a IMAX property value.<p>
     * 
     * @param newIMAX the IMAX property value to be added
     */
    void addIMAX(Integer newIMAX);

    /**
     * Removes a IMAX property value.<p>
     * 
     * @param oldIMAX the IMAX property value to be removed.
     */
    void removeIMAX(Integer oldIMAX);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#INDSC
     */
     
    /**
     * Gets all property values for the INDSC property.<p>
     * 
     * @returns a collection of values for the INDSC property.
     */
    Collection<? extends Integer> getINDSC();

    /**
     * Checks if the class has a INDSC property value.<p>
     * 
     * @return true if there is a INDSC property value.
     */
    boolean hasINDSC();

    /**
     * Adds a INDSC property value.<p>
     * 
     * @param newINDSC the INDSC property value to be added
     */
    void addINDSC(Integer newINDSC);

    /**
     * Removes a INDSC property value.<p>
     * 
     * @param oldINDSC the INDSC property value to be removed.
     */
    void removeINDSC(Integer oldINDSC);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#INTEB
     */
     
    /**
     * Gets all property values for the INTEB property.<p>
     * 
     * @returns a collection of values for the INTEB property.
     */
    Collection<? extends Integer> getINTEB();

    /**
     * Checks if the class has a INTEB property value.<p>
     * 
     * @return true if there is a INTEB property value.
     */
    boolean hasINTEB();

    /**
     * Adds a INTEB property value.<p>
     * 
     * @param newINTEB the INTEB property value to be added
     */
    void addINTEB(Integer newINTEB);

    /**
     * Removes a INTEB property value.<p>
     * 
     * @param oldINTEB the INTEB property value to be removed.
     */
    void removeINTEB(Integer oldINTEB);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#IREST
     */
     
    /**
     * Gets all property values for the IREST property.<p>
     * 
     * @returns a collection of values for the IREST property.
     */
    Collection<? extends Integer> getIREST();

    /**
     * Checks if the class has a IREST property value.<p>
     * 
     * @return true if there is a IREST property value.
     */
    boolean hasIREST();

    /**
     * Adds a IREST property value.<p>
     * 
     * @param newIREST the IREST property value to be added
     */
    void addIREST(Integer newIREST);

    /**
     * Removes a IREST property value.<p>
     * 
     * @param oldIREST the IREST property value to be removed.
     */
    void removeIREST(Integer oldIREST);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#ISOLVER
     */
     
    /**
     * Gets all property values for the ISOLVER property.<p>
     * 
     * @returns a collection of values for the ISOLVER property.
     */
    Collection<? extends Integer> getISOLVER();

    /**
     * Checks if the class has a ISOLVER property value.<p>
     * 
     * @return true if there is a ISOLVER property value.
     */
    boolean hasISOLVER();

    /**
     * Adds a ISOLVER property value.<p>
     * 
     * @param newISOLVER the ISOLVER property value to be added
     */
    void addISOLVER(Integer newISOLVER);

    /**
     * Removes a ISOLVER property value.<p>
     * 
     * @param oldISOLVER the ISOLVER property value to be removed.
     */
    void removeISOLVER(Integer oldISOLVER);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#MAXIT
     */
     
    /**
     * Gets all property values for the MAXIT property.<p>
     * 
     * @returns a collection of values for the MAXIT property.
     */
    Collection<? extends Integer> getMAXIT();

    /**
     * Checks if the class has a MAXIT property value.<p>
     * 
     * @return true if there is a MAXIT property value.
     */
    boolean hasMAXIT();

    /**
     * Adds a MAXIT property value.<p>
     * 
     * @param newMAXIT the MAXIT property value to be added
     */
    void addMAXIT(Integer newMAXIT);

    /**
     * Removes a MAXIT property value.<p>
     * 
     * @param oldMAXIT the MAXIT property value to be removed.
     */
    void removeMAXIT(Integer oldMAXIT);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#MAXTFT
     */
     
    /**
     * Gets all property values for the MAXTFT property.<p>
     * 
     * @returns a collection of values for the MAXTFT property.
     */
    Collection<? extends Integer> getMAXTFT();

    /**
     * Checks if the class has a MAXTFT property value.<p>
     * 
     * @return true if there is a MAXTFT property value.
     */
    boolean hasMAXTFT();

    /**
     * Adds a MAXTFT property value.<p>
     * 
     * @param newMAXTFT the MAXTFT property value to be added
     */
    void addMAXTFT(Integer newMAXTFT);

    /**
     * Removes a MAXTFT property value.<p>
     * 
     * @param oldMAXTFT the MAXTFT property value to be removed.
     */
    void removeMAXTFT(Integer oldMAXTFT);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#NDIN
     */
     
    /**
     * Gets all property values for the NDIN property.<p>
     * 
     * @returns a collection of values for the NDIN property.
     */
    Collection<? extends Integer> getNDIN();

    /**
     * Checks if the class has a NDIN property value.<p>
     * 
     * @return true if there is a NDIN property value.
     */
    boolean hasNDIN();

    /**
     * Adds a NDIN property value.<p>
     * 
     * @param newNDIN the NDIN property value to be added
     */
    void addNDIN(Integer newNDIN);

    /**
     * Removes a NDIN property value.<p>
     * 
     * @param oldNDIN the NDIN property value to be removed.
     */
    void removeNDIN(Integer oldNDIN);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#NJRAP
     */
     
    /**
     * Gets all property values for the NJRAP property.<p>
     * 
     * @returns a collection of values for the NJRAP property.
     */
    Collection<? extends Object> getNJRAP();

    /**
     * Checks if the class has a NJRAP property value.<p>
     * 
     * @return true if there is a NJRAP property value.
     */
    boolean hasNJRAP();

    /**
     * Adds a NJRAP property value.<p>
     * 
     * @param newNJRAP the NJRAP property value to be added
     */
    void addNJRAP(Object newNJRAP);

    /**
     * Removes a NJRAP property value.<p>
     * 
     * @param oldNJRAP the NJRAP property value to be removed.
     */
    void removeNJRAP(Object oldNJRAP);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#NPER
     */
     
    /**
     * Gets all property values for the NPER property.<p>
     * 
     * @returns a collection of values for the NPER property.
     */
    Collection<? extends Integer> getNPER();

    /**
     * Checks if the class has a NPER property value.<p>
     * 
     * @return true if there is a NPER property value.
     */
    boolean hasNPER();

    /**
     * Adds a NPER property value.<p>
     * 
     * @param newNPER the NPER property value to be added
     */
    void addNPER(Integer newNPER);

    /**
     * Removes a NPER property value.<p>
     * 
     * @param oldNPER the NPER property value to be removed.
     */
    void removeNPER(Integer oldNPER);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#NTABFT
     */
     
    /**
     * Gets all property values for the NTABFT property.<p>
     * 
     * @returns a collection of values for the NTABFT property.
     */
    Collection<? extends Integer> getNTABFT();

    /**
     * Checks if the class has a NTABFT property value.<p>
     * 
     * @return true if there is a NTABFT property value.
     */
    boolean hasNTABFT();

    /**
     * Adds a NTABFT property value.<p>
     * 
     * @param newNTABFT the NTABFT property value to be added
     */
    void addNTABFT(Integer newNTABFT);

    /**
     * Removes a NTABFT property value.<p>
     * 
     * @param oldNTABFT the NTABFT property value to be removed.
     */
    void removeNTABFT(Integer oldNTABFT);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#PRINT
     */
     
    /**
     * Gets all property values for the PRINT property.<p>
     * 
     * @returns a collection of values for the PRINT property.
     */
    Collection<? extends Integer> getPRINT();

    /**
     * Checks if the class has a PRINT property value.<p>
     * 
     * @return true if there is a PRINT property value.
     */
    boolean hasPRINT();

    /**
     * Adds a PRINT property value.<p>
     * 
     * @param newPRINT the PRINT property value to be added
     */
    void addPRINT(Integer newPRINT);

    /**
     * Removes a PRINT property value.<p>
     * 
     * @param oldPRINT the PRINT property value to be removed.
     */
    void removePRINT(Integer oldPRINT);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#STOP
     */
     
    /**
     * Gets all property values for the STOP property.<p>
     * 
     * @returns a collection of values for the STOP property.
     */
    Collection<? extends String> getSTOP();

    /**
     * Checks if the class has a STOP property value.<p>
     * 
     * @return true if there is a STOP property value.
     */
    boolean hasSTOP();

    /**
     * Adds a STOP property value.<p>
     * 
     * @param newSTOP the STOP property value to be added
     */
    void addSTOP(String newSTOP);

    /**
     * Removes a STOP property value.<p>
     * 
     * @param oldSTOP the STOP property value to be removed.
     */
    void removeSTOP(String oldSTOP);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#numberOfTimesSteps
     */
     
    /**
     * Gets all property values for the numberOfTimesSteps property.<p>
     * 
     * @returns a collection of values for the numberOfTimesSteps property.
     */
    Collection<? extends Integer> getNumberOfTimesSteps();

    /**
     * Checks if the class has a numberOfTimesSteps property value.<p>
     * 
     * @return true if there is a numberOfTimesSteps property value.
     */
    boolean hasNumberOfTimesSteps();

    /**
     * Adds a numberOfTimesSteps property value.<p>
     * 
     * @param newNumberOfTimesSteps the numberOfTimesSteps property value to be added
     */
    void addNumberOfTimesSteps(Integer newNumberOfTimesSteps);

    /**
     * Removes a numberOfTimesSteps property value.<p>
     * 
     * @param oldNumberOfTimesSteps the numberOfTimesSteps property value to be removed.
     */
    void removeNumberOfTimesSteps(Integer oldNumberOfTimesSteps);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#timeStepDuration
     */
     
    /**
     * Gets all property values for the timeStepDuration property.<p>
     * 
     * @returns a collection of values for the timeStepDuration property.
     */
    Collection<? extends Object> getTimeStepDuration();

    /**
     * Checks if the class has a timeStepDuration property value.<p>
     * 
     * @return true if there is a timeStepDuration property value.
     */
    boolean hasTimeStepDuration();

    /**
     * Adds a timeStepDuration property value.<p>
     * 
     * @param newTimeStepDuration the timeStepDuration property value to be added
     */
    void addTimeStepDuration(Object newTimeStepDuration);

    /**
     * Removes a timeStepDuration property value.<p>
     * 
     * @param oldTimeStepDuration the timeStepDuration property value to be removed.
     */
    void removeTimeStepDuration(Object oldTimeStepDuration);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
