package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Subdomain <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface Subdomain extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasNode
     */
     
    /**
     * Gets all property values for the hasNode property.<p>
     * 
     * @returns a collection of values for the hasNode property.
     */
    Collection<? extends Node> getHasNode();

    /**
     * Checks if the class has a hasNode property value.<p>
     * 
     * @return true if there is a hasNode property value.
     */
    boolean hasHasNode();

    /**
     * Adds a hasNode property value.<p>
     * 
     * @param newHasNode the hasNode property value to be added
     */
    void addHasNode(Node newHasNode);

    /**
     * Removes a hasNode property value.<p>
     * 
     * @param oldHasNode the hasNode property value to be removed.
     */
    void removeHasNode(Node oldHasNode);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
