package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: UNVBlockSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */

public interface UNVBlockSettings extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areUNVBlockSettingsOf
     */
     
    /**
     * Gets all property values for the areUNVBlockSettingsOf property.<p>
     * 
     * @returns a collection of values for the areUNVBlockSettingsOf property.
     */
    Collection<? extends UNVBlock> getAreUNVBlockSettingsOf();

    /**
     * Checks if the class has a areUNVBlockSettingsOf property value.<p>
     * 
     * @return true if there is a areUNVBlockSettingsOf property value.
     */
    boolean hasAreUNVBlockSettingsOf();

    /**
     * Adds a areUNVBlockSettingsOf property value.<p>
     * 
     * @param newAreUNVBlockSettingsOf the areUNVBlockSettingsOf property value to be added
     */
    void addAreUNVBlockSettingsOf(UNVBlock newAreUNVBlockSettingsOf);

    /**
     * Removes a areUNVBlockSettingsOf property value.<p>
     * 
     * @param oldAreUNVBlockSettingsOf the areUNVBlockSettingsOf property value to be removed.
     */
    void removeAreUNVBlockSettingsOf(UNVBlock oldAreUNVBlockSettingsOf);


    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#UNVBlockEndMarker
     */
     
    /**
     * Gets all property values for the UNVBlockEndMarker property.<p>
     * 
     * @returns a collection of values for the UNVBlockEndMarker property.
     */
    Collection<? extends Integer> getUNVBlockEndMarker();

    /**
     * Checks if the class has a UNVBlockEndMarker property value.<p>
     * 
     * @return true if there is a UNVBlockEndMarker property value.
     */
    boolean hasUNVBlockEndMarker();

    /**
     * Adds a UNVBlockEndMarker property value.<p>
     * 
     * @param newUNVBlockEndMarker the UNVBlockEndMarker property value to be added
     */
    void addUNVBlockEndMarker(Integer newUNVBlockEndMarker);

    /**
     * Removes a UNVBlockEndMarker property value.<p>
     * 
     * @param oldUNVBlockEndMarker the UNVBlockEndMarker property value to be removed.
     */
    void removeUNVBlockEndMarker(Integer oldUNVBlockEndMarker);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#UNVBlockIDPartOne
     */
     
    /**
     * Gets all property values for the UNVBlockIDPartOne property.<p>
     * 
     * @returns a collection of values for the UNVBlockIDPartOne property.
     */
    Collection<? extends Integer> getUNVBlockIDPartOne();

    /**
     * Checks if the class has a UNVBlockIDPartOne property value.<p>
     * 
     * @return true if there is a UNVBlockIDPartOne property value.
     */
    boolean hasUNVBlockIDPartOne();

    /**
     * Adds a UNVBlockIDPartOne property value.<p>
     * 
     * @param newUNVBlockIDPartOne the UNVBlockIDPartOne property value to be added
     */
    void addUNVBlockIDPartOne(Integer newUNVBlockIDPartOne);

    /**
     * Removes a UNVBlockIDPartOne property value.<p>
     * 
     * @param oldUNVBlockIDPartOne the UNVBlockIDPartOne property value to be removed.
     */
    void removeUNVBlockIDPartOne(Integer oldUNVBlockIDPartOne);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#UNVBlockIDPartTwo
     */
     
    /**
     * Gets all property values for the UNVBlockIDPartTwo property.<p>
     * 
     * @returns a collection of values for the UNVBlockIDPartTwo property.
     */
    Collection<? extends Integer> getUNVBlockIDPartTwo();

    /**
     * Checks if the class has a UNVBlockIDPartTwo property value.<p>
     * 
     * @return true if there is a UNVBlockIDPartTwo property value.
     */
    boolean hasUNVBlockIDPartTwo();

    /**
     * Adds a UNVBlockIDPartTwo property value.<p>
     * 
     * @param newUNVBlockIDPartTwo the UNVBlockIDPartTwo property value to be added
     */
    void addUNVBlockIDPartTwo(Integer newUNVBlockIDPartTwo);

    /**
     * Removes a UNVBlockIDPartTwo property value.<p>
     * 
     * @param oldUNVBlockIDPartTwo the UNVBlockIDPartTwo property value to be removed.
     */
    void removeUNVBlockIDPartTwo(Integer oldUNVBlockIDPartTwo);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#UNVBlockStartMarker
     */
     
    /**
     * Gets all property values for the UNVBlockStartMarker property.<p>
     * 
     * @returns a collection of values for the UNVBlockStartMarker property.
     */
    Collection<? extends Integer> getUNVBlockStartMarker();

    /**
     * Checks if the class has a UNVBlockStartMarker property value.<p>
     * 
     * @return true if there is a UNVBlockStartMarker property value.
     */
    boolean hasUNVBlockStartMarker();

    /**
     * Adds a UNVBlockStartMarker property value.<p>
     * 
     * @param newUNVBlockStartMarker the UNVBlockStartMarker property value to be added
     */
    void addUNVBlockStartMarker(Integer newUNVBlockStartMarker);

    /**
     * Removes a UNVBlockStartMarker property value.<p>
     * 
     * @param oldUNVBlockStartMarker the UNVBlockStartMarker property value to be removed.
     */
    void removeUNVBlockStartMarker(Integer oldUNVBlockStartMarker);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedConstraintBlockValue1
     */
     
    /**
     * Gets all property values for the hasUnusedConstraintBlockValue1 property.<p>
     * 
     * @returns a collection of values for the hasUnusedConstraintBlockValue1 property.
     */
    Collection<? extends Integer> getHasUnusedConstraintBlockValue1();

    /**
     * Checks if the class has a hasUnusedConstraintBlockValue1 property value.<p>
     * 
     * @return true if there is a hasUnusedConstraintBlockValue1 property value.
     */
    boolean hasHasUnusedConstraintBlockValue1();

    /**
     * Adds a hasUnusedConstraintBlockValue1 property value.<p>
     * 
     * @param newHasUnusedConstraintBlockValue1 the hasUnusedConstraintBlockValue1 property value to be added
     */
    void addHasUnusedConstraintBlockValue1(Integer newHasUnusedConstraintBlockValue1);

    /**
     * Removes a hasUnusedConstraintBlockValue1 property value.<p>
     * 
     * @param oldHasUnusedConstraintBlockValue1 the hasUnusedConstraintBlockValue1 property value to be removed.
     */
    void removeHasUnusedConstraintBlockValue1(Integer oldHasUnusedConstraintBlockValue1);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedConstraintBlockValue2
     */
     
    /**
     * Gets all property values for the hasUnusedConstraintBlockValue2 property.<p>
     * 
     * @returns a collection of values for the hasUnusedConstraintBlockValue2 property.
     */
    Collection<? extends String> getHasUnusedConstraintBlockValue2();

    /**
     * Checks if the class has a hasUnusedConstraintBlockValue2 property value.<p>
     * 
     * @return true if there is a hasUnusedConstraintBlockValue2 property value.
     */
    boolean hasHasUnusedConstraintBlockValue2();

    /**
     * Adds a hasUnusedConstraintBlockValue2 property value.<p>
     * 
     * @param newHasUnusedConstraintBlockValue2 the hasUnusedConstraintBlockValue2 property value to be added
     */
    void addHasUnusedConstraintBlockValue2(String newHasUnusedConstraintBlockValue2);

    /**
     * Removes a hasUnusedConstraintBlockValue2 property value.<p>
     * 
     * @param oldHasUnusedConstraintBlockValue2 the hasUnusedConstraintBlockValue2 property value to be removed.
     */
    void removeHasUnusedConstraintBlockValue2(String oldHasUnusedConstraintBlockValue2);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedConstraintBlockValue3
     */
     
    /**
     * Gets all property values for the hasUnusedConstraintBlockValue3 property.<p>
     * 
     * @returns a collection of values for the hasUnusedConstraintBlockValue3 property.
     */
    Collection<? extends Integer> getHasUnusedConstraintBlockValue3();

    /**
     * Checks if the class has a hasUnusedConstraintBlockValue3 property value.<p>
     * 
     * @return true if there is a hasUnusedConstraintBlockValue3 property value.
     */
    boolean hasHasUnusedConstraintBlockValue3();

    /**
     * Adds a hasUnusedConstraintBlockValue3 property value.<p>
     * 
     * @param newHasUnusedConstraintBlockValue3 the hasUnusedConstraintBlockValue3 property value to be added
     */
    void addHasUnusedConstraintBlockValue3(Integer newHasUnusedConstraintBlockValue3);

    /**
     * Removes a hasUnusedConstraintBlockValue3 property value.<p>
     * 
     * @param oldHasUnusedConstraintBlockValue3 the hasUnusedConstraintBlockValue3 property value to be removed.
     */
    void removeHasUnusedConstraintBlockValue3(Integer oldHasUnusedConstraintBlockValue3);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue1
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue1 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue1 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue1();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue1 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue1 property value.
     */
    boolean hasHasUnusedResultsBlockValue1();

    /**
     * Adds a hasUnusedResultsBlockValue1 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue1 the hasUnusedResultsBlockValue1 property value to be added
     */
    void addHasUnusedResultsBlockValue1(Integer newHasUnusedResultsBlockValue1);

    /**
     * Removes a hasUnusedResultsBlockValue1 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue1 the hasUnusedResultsBlockValue1 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue1(Integer oldHasUnusedResultsBlockValue1);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue2
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue2 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue2 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue2();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue2 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue2 property value.
     */
    boolean hasHasUnusedResultsBlockValue2();

    /**
     * Adds a hasUnusedResultsBlockValue2 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue2 the hasUnusedResultsBlockValue2 property value to be added
     */
    void addHasUnusedResultsBlockValue2(Integer newHasUnusedResultsBlockValue2);

    /**
     * Removes a hasUnusedResultsBlockValue2 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue2 the hasUnusedResultsBlockValue2 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue2(Integer oldHasUnusedResultsBlockValue2);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue3
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue3 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue3 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue3();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue3 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue3 property value.
     */
    boolean hasHasUnusedResultsBlockValue3();

    /**
     * Adds a hasUnusedResultsBlockValue3 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue3 the hasUnusedResultsBlockValue3 property value to be added
     */
    void addHasUnusedResultsBlockValue3(Integer newHasUnusedResultsBlockValue3);

    /**
     * Removes a hasUnusedResultsBlockValue3 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue3 the hasUnusedResultsBlockValue3 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue3(Integer oldHasUnusedResultsBlockValue3);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue4
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue4 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue4 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue4();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue4 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue4 property value.
     */
    boolean hasHasUnusedResultsBlockValue4();

    /**
     * Adds a hasUnusedResultsBlockValue4 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue4 the hasUnusedResultsBlockValue4 property value to be added
     */
    void addHasUnusedResultsBlockValue4(Integer newHasUnusedResultsBlockValue4);

    /**
     * Removes a hasUnusedResultsBlockValue4 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue4 the hasUnusedResultsBlockValue4 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue4(Integer oldHasUnusedResultsBlockValue4);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue5
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue5 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue5 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue5();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue5 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue5 property value.
     */
    boolean hasHasUnusedResultsBlockValue5();

    /**
     * Adds a hasUnusedResultsBlockValue5 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue5 the hasUnusedResultsBlockValue5 property value to be added
     */
    void addHasUnusedResultsBlockValue5(Integer newHasUnusedResultsBlockValue5);

    /**
     * Removes a hasUnusedResultsBlockValue5 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue5 the hasUnusedResultsBlockValue5 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue5(Integer oldHasUnusedResultsBlockValue5);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue6
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue6 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue6 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue6();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue6 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue6 property value.
     */
    boolean hasHasUnusedResultsBlockValue6();

    /**
     * Adds a hasUnusedResultsBlockValue6 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue6 the hasUnusedResultsBlockValue6 property value to be added
     */
    void addHasUnusedResultsBlockValue6(Integer newHasUnusedResultsBlockValue6);

    /**
     * Removes a hasUnusedResultsBlockValue6 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue6 the hasUnusedResultsBlockValue6 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue6(Integer oldHasUnusedResultsBlockValue6);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue7
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue7 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue7 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue7();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue7 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue7 property value.
     */
    boolean hasHasUnusedResultsBlockValue7();

    /**
     * Adds a hasUnusedResultsBlockValue7 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue7 the hasUnusedResultsBlockValue7 property value to be added
     */
    void addHasUnusedResultsBlockValue7(Integer newHasUnusedResultsBlockValue7);

    /**
     * Removes a hasUnusedResultsBlockValue7 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue7 the hasUnusedResultsBlockValue7 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue7(Integer oldHasUnusedResultsBlockValue7);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue8
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue8 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue8 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue8();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue8 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue8 property value.
     */
    boolean hasHasUnusedResultsBlockValue8();

    /**
     * Adds a hasUnusedResultsBlockValue8 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue8 the hasUnusedResultsBlockValue8 property value to be added
     */
    void addHasUnusedResultsBlockValue8(Integer newHasUnusedResultsBlockValue8);

    /**
     * Removes a hasUnusedResultsBlockValue8 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue8 the hasUnusedResultsBlockValue8 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue8(Integer oldHasUnusedResultsBlockValue8);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue9
     */
     
    /**
     * Gets all property values for the hasUnusedResultsBlockValue9 property.<p>
     * 
     * @returns a collection of values for the hasUnusedResultsBlockValue9 property.
     */
    Collection<? extends Integer> getHasUnusedResultsBlockValue9();

    /**
     * Checks if the class has a hasUnusedResultsBlockValue9 property value.<p>
     * 
     * @return true if there is a hasUnusedResultsBlockValue9 property value.
     */
    boolean hasHasUnusedResultsBlockValue9();

    /**
     * Adds a hasUnusedResultsBlockValue9 property value.<p>
     * 
     * @param newHasUnusedResultsBlockValue9 the hasUnusedResultsBlockValue9 property value to be added
     */
    void addHasUnusedResultsBlockValue9(Integer newHasUnusedResultsBlockValue9);

    /**
     * Removes a hasUnusedResultsBlockValue9 property value.<p>
     * 
     * @param oldHasUnusedResultsBlockValue9 the hasUnusedResultsBlockValue9 property value to be removed.
     */
    void removeHasUnusedResultsBlockValue9(Integer oldHasUnusedResultsBlockValue9);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
