package eu.sifem.model.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: VectorValue <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */

public interface VectorValue extends Value {

    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasInputStatus
     */
     
    /**
     * Gets all property values for the hasInputStatus property.<p>
     * 
     * @returns a collection of values for the hasInputStatus property.
     */
    Collection<? extends Object> getHasInputStatus();

    /**
     * Checks if the class has a hasInputStatus property value.<p>
     * 
     * @return true if there is a hasInputStatus property value.
     */
    boolean hasHasInputStatus();

    /**
     * Adds a hasInputStatus property value.<p>
     * 
     * @param newHasInputStatus the hasInputStatus property value to be added
     */
    void addHasInputStatus(Object newHasInputStatus);

    /**
     * Removes a hasInputStatus property value.<p>
     * 
     * @param oldHasInputStatus the hasInputStatus property value to be removed.
     */
    void removeHasInputStatus(Object oldHasInputStatus);



    /* ***************************************************
     * Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasVectorDataValue
     */
     
    /**
     * Gets all property values for the hasVectorDataValue property.<p>
     * 
     * @returns a collection of values for the hasVectorDataValue property.
     */
    Collection<? extends Object> getHasVectorDataValue();

    /**
     * Checks if the class has a hasVectorDataValue property value.<p>
     * 
     * @return true if there is a hasVectorDataValue property value.
     */
    boolean hasHasVectorDataValue();

    /**
     * Adds a hasVectorDataValue property value.<p>
     * 
     * @param newHasVectorDataValue the hasVectorDataValue property value to be added
     */
    void addHasVectorDataValue(Object newHasVectorDataValue);

    /**
     * Removes a hasVectorDataValue property value.<p>
     * 
     * @param oldHasVectorDataValue the hasVectorDataValue property value to be removed.
     */
    void removeHasVectorDataValue(Object oldHasVectorDataValue);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
