package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultEquation <br>
 * @version generated on Mon May 11 16:25:18 BST 2015 by jbjares
 */
public class DefaultEquation extends WrappedIndividualImpl implements Equation {

    public DefaultEquation(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://codata.jp/OML-Property.owl#Eq
     */
     
    public Collection<? extends Object> getEq() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EQ, Object.class);
    }

    public boolean hasEq() {
		return !getEq().isEmpty();
    }

    public void addEq(Object newEq) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EQ, newEq);
    }

    public void removeEq(Object oldEq) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_EQ, oldEq);
    }


}
