package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMesh <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */
public class DefaultMesh extends WrappedIndividualImpl implements Mesh {

    public DefaultMesh(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasMeshSettings
     */
     
    public Collection<? extends MeshSettings> getHasMeshSettings() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASMESHSETTINGS,
                                               DefaultMeshSettings.class);
    }

    public boolean hasHasMeshSettings() {
	   return !getHasMeshSettings().isEmpty();
    }

    public void addHasMeshSettings(MeshSettings newHasMeshSettings) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASMESHSETTINGS,
                                       newHasMeshSettings);
    }

    public void removeHasMeshSettings(MeshSettings oldHasMeshSettings) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASMESHSETTINGS,
                                          oldHasMeshSettings);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#discretizes
     */
     
    public Collection<? extends Finite_Element_Model_Domain> getDiscretizes() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_DISCRETIZES,
                                               DefaultFinite_Element_Model_Domain.class);
    }

    public boolean hasDiscretizes() {
	   return !getDiscretizes().isEmpty();
    }

    public void addDiscretizes(Finite_Element_Model_Domain newDiscretizes) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_DISCRETIZES,
                                       newDiscretizes);
    }

    public void removeDiscretizes(Finite_Element_Model_Domain oldDiscretizes) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_DISCRETIZES,
                                          oldDiscretizes);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isMeshOf
     */
     
    public Collection<? extends Discrete_Model> getIsMeshOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISMESHOF,
                                               DefaultDiscrete_Model.class);
    }

    public boolean hasIsMeshOf() {
	   return !getIsMeshOf().isEmpty();
    }

    public void addIsMeshOf(Discrete_Model newIsMeshOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISMESHOF,
                                       newIsMeshOf);
    }

    public void removeIsMeshOf(Discrete_Model oldIsMeshOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISMESHOF,
                                          oldIsMeshOf);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasMaximumNumberOfNodesPerElement
     */
     
    public Collection<? extends Integer> getHasMaximumNumberOfNodesPerElement() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAXIMUMNUMBEROFNODESPERELEMENT, Integer.class);
    }

    public boolean hasHasMaximumNumberOfNodesPerElement() {
		return !getHasMaximumNumberOfNodesPerElement().isEmpty();
    }

    public void addHasMaximumNumberOfNodesPerElement(Integer newHasMaximumNumberOfNodesPerElement) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAXIMUMNUMBEROFNODESPERELEMENT, newHasMaximumNumberOfNodesPerElement);
    }

    public void removeHasMaximumNumberOfNodesPerElement(Integer oldHasMaximumNumberOfNodesPerElement) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMAXIMUMNUMBEROFNODESPERELEMENT, oldHasMaximumNumberOfNodesPerElement);
    }


}
