package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultUNVBlockSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */
public class DefaultUNVBlockSettings extends WrappedIndividualImpl implements UNVBlockSettings {

    public DefaultUNVBlockSettings(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areUNVBlockSettingsOf
     */
     
    public Collection<? extends UNVBlock> getAreUNVBlockSettingsOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AREUNVBLOCKSETTINGSOF,
                                               DefaultUNVBlock.class);
    }

    public boolean hasAreUNVBlockSettingsOf() {
	   return !getAreUNVBlockSettingsOf().isEmpty();
    }

    public void addAreUNVBlockSettingsOf(UNVBlock newAreUNVBlockSettingsOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AREUNVBLOCKSETTINGSOF,
                                       newAreUNVBlockSettingsOf);
    }

    public void removeAreUNVBlockSettingsOf(UNVBlock oldAreUNVBlockSettingsOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AREUNVBLOCKSETTINGSOF,
                                          oldAreUNVBlockSettingsOf);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#UNVBlockEndMarker
     */
     
    public Collection<? extends Integer> getUNVBlockEndMarker() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKENDMARKER, Integer.class);
    }

    public boolean hasUNVBlockEndMarker() {
		return !getUNVBlockEndMarker().isEmpty();
    }

    public void addUNVBlockEndMarker(Integer newUNVBlockEndMarker) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKENDMARKER, newUNVBlockEndMarker);
    }

    public void removeUNVBlockEndMarker(Integer oldUNVBlockEndMarker) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKENDMARKER, oldUNVBlockEndMarker);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#UNVBlockIDPartOne
     */
     
    public Collection<? extends Integer> getUNVBlockIDPartOne() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKIDPARTONE, Integer.class);
    }

    public boolean hasUNVBlockIDPartOne() {
		return !getUNVBlockIDPartOne().isEmpty();
    }

    public void addUNVBlockIDPartOne(Integer newUNVBlockIDPartOne) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKIDPARTONE, newUNVBlockIDPartOne);
    }

    public void removeUNVBlockIDPartOne(Integer oldUNVBlockIDPartOne) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKIDPARTONE, oldUNVBlockIDPartOne);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#UNVBlockIDPartTwo
     */
     
    public Collection<? extends Integer> getUNVBlockIDPartTwo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKIDPARTTWO, Integer.class);
    }

    public boolean hasUNVBlockIDPartTwo() {
		return !getUNVBlockIDPartTwo().isEmpty();
    }

    public void addUNVBlockIDPartTwo(Integer newUNVBlockIDPartTwo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKIDPARTTWO, newUNVBlockIDPartTwo);
    }

    public void removeUNVBlockIDPartTwo(Integer oldUNVBlockIDPartTwo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKIDPARTTWO, oldUNVBlockIDPartTwo);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#UNVBlockStartMarker
     */
     
    public Collection<? extends Integer> getUNVBlockStartMarker() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKSTARTMARKER, Integer.class);
    }

    public boolean hasUNVBlockStartMarker() {
		return !getUNVBlockStartMarker().isEmpty();
    }

    public void addUNVBlockStartMarker(Integer newUNVBlockStartMarker) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKSTARTMARKER, newUNVBlockStartMarker);
    }

    public void removeUNVBlockStartMarker(Integer oldUNVBlockStartMarker) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_UNVBLOCKSTARTMARKER, oldUNVBlockStartMarker);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedConstraintBlockValue1
     */
     
    public Collection<? extends Integer> getHasUnusedConstraintBlockValue1() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE1, Integer.class);
    }

    public boolean hasHasUnusedConstraintBlockValue1() {
		return !getHasUnusedConstraintBlockValue1().isEmpty();
    }

    public void addHasUnusedConstraintBlockValue1(Integer newHasUnusedConstraintBlockValue1) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE1, newHasUnusedConstraintBlockValue1);
    }

    public void removeHasUnusedConstraintBlockValue1(Integer oldHasUnusedConstraintBlockValue1) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE1, oldHasUnusedConstraintBlockValue1);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedConstraintBlockValue2
     */
     
    public Collection<? extends String> getHasUnusedConstraintBlockValue2() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE2, String.class);
    }

    public boolean hasHasUnusedConstraintBlockValue2() {
		return !getHasUnusedConstraintBlockValue2().isEmpty();
    }

    public void addHasUnusedConstraintBlockValue2(String newHasUnusedConstraintBlockValue2) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE2, newHasUnusedConstraintBlockValue2);
    }

    public void removeHasUnusedConstraintBlockValue2(String oldHasUnusedConstraintBlockValue2) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE2, oldHasUnusedConstraintBlockValue2);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedConstraintBlockValue3
     */
     
    public Collection<? extends Integer> getHasUnusedConstraintBlockValue3() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE3, Integer.class);
    }

    public boolean hasHasUnusedConstraintBlockValue3() {
		return !getHasUnusedConstraintBlockValue3().isEmpty();
    }

    public void addHasUnusedConstraintBlockValue3(Integer newHasUnusedConstraintBlockValue3) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE3, newHasUnusedConstraintBlockValue3);
    }

    public void removeHasUnusedConstraintBlockValue3(Integer oldHasUnusedConstraintBlockValue3) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDCONSTRAINTBLOCKVALUE3, oldHasUnusedConstraintBlockValue3);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue1
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue1() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE1, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue1() {
		return !getHasUnusedResultsBlockValue1().isEmpty();
    }

    public void addHasUnusedResultsBlockValue1(Integer newHasUnusedResultsBlockValue1) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE1, newHasUnusedResultsBlockValue1);
    }

    public void removeHasUnusedResultsBlockValue1(Integer oldHasUnusedResultsBlockValue1) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE1, oldHasUnusedResultsBlockValue1);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue2
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue2() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE2, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue2() {
		return !getHasUnusedResultsBlockValue2().isEmpty();
    }

    public void addHasUnusedResultsBlockValue2(Integer newHasUnusedResultsBlockValue2) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE2, newHasUnusedResultsBlockValue2);
    }

    public void removeHasUnusedResultsBlockValue2(Integer oldHasUnusedResultsBlockValue2) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE2, oldHasUnusedResultsBlockValue2);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue3
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue3() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE3, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue3() {
		return !getHasUnusedResultsBlockValue3().isEmpty();
    }

    public void addHasUnusedResultsBlockValue3(Integer newHasUnusedResultsBlockValue3) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE3, newHasUnusedResultsBlockValue3);
    }

    public void removeHasUnusedResultsBlockValue3(Integer oldHasUnusedResultsBlockValue3) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE3, oldHasUnusedResultsBlockValue3);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue4
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue4() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE4, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue4() {
		return !getHasUnusedResultsBlockValue4().isEmpty();
    }

    public void addHasUnusedResultsBlockValue4(Integer newHasUnusedResultsBlockValue4) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE4, newHasUnusedResultsBlockValue4);
    }

    public void removeHasUnusedResultsBlockValue4(Integer oldHasUnusedResultsBlockValue4) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE4, oldHasUnusedResultsBlockValue4);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue5
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue5() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE5, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue5() {
		return !getHasUnusedResultsBlockValue5().isEmpty();
    }

    public void addHasUnusedResultsBlockValue5(Integer newHasUnusedResultsBlockValue5) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE5, newHasUnusedResultsBlockValue5);
    }

    public void removeHasUnusedResultsBlockValue5(Integer oldHasUnusedResultsBlockValue5) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE5, oldHasUnusedResultsBlockValue5);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue6
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue6() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE6, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue6() {
		return !getHasUnusedResultsBlockValue6().isEmpty();
    }

    public void addHasUnusedResultsBlockValue6(Integer newHasUnusedResultsBlockValue6) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE6, newHasUnusedResultsBlockValue6);
    }

    public void removeHasUnusedResultsBlockValue6(Integer oldHasUnusedResultsBlockValue6) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE6, oldHasUnusedResultsBlockValue6);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue7
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue7() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE7, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue7() {
		return !getHasUnusedResultsBlockValue7().isEmpty();
    }

    public void addHasUnusedResultsBlockValue7(Integer newHasUnusedResultsBlockValue7) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE7, newHasUnusedResultsBlockValue7);
    }

    public void removeHasUnusedResultsBlockValue7(Integer oldHasUnusedResultsBlockValue7) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE7, oldHasUnusedResultsBlockValue7);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue8
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue8() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE8, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue8() {
		return !getHasUnusedResultsBlockValue8().isEmpty();
    }

    public void addHasUnusedResultsBlockValue8(Integer newHasUnusedResultsBlockValue8) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE8, newHasUnusedResultsBlockValue8);
    }

    public void removeHasUnusedResultsBlockValue8(Integer oldHasUnusedResultsBlockValue8) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE8, oldHasUnusedResultsBlockValue8);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedResultsBlockValue9
     */
     
    public Collection<? extends Integer> getHasUnusedResultsBlockValue9() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE9, Integer.class);
    }

    public boolean hasHasUnusedResultsBlockValue9() {
		return !getHasUnusedResultsBlockValue9().isEmpty();
    }

    public void addHasUnusedResultsBlockValue9(Integer newHasUnusedResultsBlockValue9) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE9, newHasUnusedResultsBlockValue9);
    }

    public void removeHasUnusedResultsBlockValue9(Integer oldHasUnusedResultsBlockValue9) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDRESULTSBLOCKVALUE9, oldHasUnusedResultsBlockValue9);
    }


}
