package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultFinite_element <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */
public class DefaultFinite_element extends WrappedIndividualImpl implements Finite_element {

    public DefaultFinite_element(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasElementSettings
     */
     
    public Collection<? extends ElementSettings> getHasElementSettings() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASELEMENTSETTINGS,
                                               DefaultElementSettings.class);
    }

    public boolean hasHasElementSettings() {
	   return !getHasElementSettings().isEmpty();
    }

    public void addHasElementSettings(ElementSettings newHasElementSettings) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASELEMENTSETTINGS,
                                       newHasElementSettings);
    }

    public void removeHasElementSettings(ElementSettings oldHasElementSettings) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASELEMENTSETTINGS,
                                          oldHasElementSettings);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasNode
     */
     
    public Collection<? extends Node> getHasNode() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASNODE,
                                               DefaultNode.class);
    }

    public boolean hasHasNode() {
	   return !getHasNode().isEmpty();
    }

    public void addHasNode(Node newHasNode) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASNODE,
                                       newHasNode);
    }

    public void removeHasNode(Node oldHasNode) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASNODE,
                                          oldHasNode);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasElementNumber
     */
     
    public Collection<? extends Integer> getHasElementNumber() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASELEMENTNUMBER, Integer.class);
    }

    public boolean hasHasElementNumber() {
		return !getHasElementNumber().isEmpty();
    }

    public void addHasElementNumber(Integer newHasElementNumber) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASELEMENTNUMBER, newHasElementNumber);
    }

    public void removeHasElementNumber(Integer oldHasElementNumber) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASELEMENTNUMBER, oldHasElementNumber);
    }


}
