package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultUNVOutputFile <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */
public class DefaultUNVOutputFile extends WrappedIndividualImpl implements UNVOutputFile {

    public DefaultUNVOutputFile(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUNVBlock
     */
     
    public Collection<? extends UNVBlock> getHasUNVBlock() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASUNVBLOCK,
                                               DefaultUNVBlock.class);
    }

    public boolean hasHasUNVBlock() {
	   return !getHasUNVBlock().isEmpty();
    }

    public void addHasUNVBlock(UNVBlock newHasUNVBlock) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASUNVBLOCK,
                                       newHasUNVBlock);
    }

    public void removeHasUNVBlock(UNVBlock oldHasUNVBlock) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASUNVBLOCK,
                                          oldHasUNVBlock);
    }


}
