package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAgentInfluence <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */
public class DefaultAgentInfluence extends WrappedIndividualImpl implements AgentInfluence {

    public DefaultAgentInfluence(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#agent
     */
     
    public Collection<? extends Agent> getAgent() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AGENT,
                                               DefaultAgent.class);
    }

    public boolean hasAgent() {
	   return !getAgent().isEmpty();
    }

    public void addAgent(Agent newAgent) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AGENT,
                                       newAgent);
    }

    public void removeAgent(Agent oldAgent) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AGENT,
                                          oldAgent);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#hadActivity
     */
     
    public Collection<? extends Activity> getHadActivity() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HADACTIVITY,
                                               DefaultActivity.class);
    }

    public boolean hasHadActivity() {
	   return !getHadActivity().isEmpty();
    }

    public void addHadActivity(Activity newHadActivity) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HADACTIVITY,
                                       newHadActivity);
    }

    public void removeHadActivity(Activity oldHadActivity) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HADACTIVITY,
                                          oldHadActivity);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#hadRole
     */
     
    public Collection<? extends Role> getHadRole() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HADROLE,
                                               DefaultRole.class);
    }

    public boolean hasHadRole() {
	   return !getHadRole().isEmpty();
    }

    public void addHadRole(Role newHadRole) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HADROLE,
                                       newHadRole);
    }

    public void removeHadRole(Role oldHadRole) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HADROLE,
                                          oldHadRole);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#influencer
     */
     
    public Collection<? extends WrappedIndividual> getInfluencer() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INFLUENCER,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasInfluencer() {
	   return !getInfluencer().isEmpty();
    }

    public void addInfluencer(WrappedIndividual newInfluencer) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INFLUENCER,
                                       newInfluencer);
    }

    public void removeInfluencer(WrappedIndividual oldInfluencer) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INFLUENCER,
                                          oldInfluencer);
    }


}
