package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultFinite_Element_Model_Domain <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */
public class DefaultFinite_Element_Model_Domain extends WrappedIndividualImpl implements Finite_Element_Model_Domain {

    public DefaultFinite_Element_Model_Domain(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasDomainSettings
     */
     
    public Collection<? extends DomainSettings> getHasDomainSettings() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASDOMAINSETTINGS,
                                               DefaultDomainSettings.class);
    }

    public boolean hasHasDomainSettings() {
	   return !getHasDomainSettings().isEmpty();
    }

    public void addHasDomainSettings(DomainSettings newHasDomainSettings) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASDOMAINSETTINGS,
                                       newHasDomainSettings);
    }

    public void removeHasDomainSettings(DomainSettings oldHasDomainSettings) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASDOMAINSETTINGS,
                                          oldHasDomainSettings);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasLoad
     */
     
    public Collection<? extends Loading_> getHasLoad() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASLOAD,
                                               DefaultLoading_.class);
    }

    public boolean hasHasLoad() {
	   return !getHasLoad().isEmpty();
    }

    public void addHasLoad(Loading_ newHasLoad) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASLOAD,
                                       newHasLoad);
    }

    public void removeHasLoad(Loading_ oldHasLoad) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASLOAD,
                                          oldHasLoad);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isDiscretizedBy
     */
     
    public Collection<? extends Mesh> getIsDiscretizedBy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISDISCRETIZEDBY,
                                               DefaultMesh.class);
    }

    public boolean hasIsDiscretizedBy() {
	   return !getIsDiscretizedBy().isEmpty();
    }

    public void addIsDiscretizedBy(Mesh newIsDiscretizedBy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISDISCRETIZEDBY,
                                       newIsDiscretizedBy);
    }

    public void removeIsDiscretizedBy(Mesh oldIsDiscretizedBy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISDISCRETIZEDBY,
                                          oldIsDiscretizedBy);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isDomainOf
     */
     
    public Collection<? extends Mathematical_Model> getIsDomainOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISDOMAINOF,
                                               DefaultMathematical_Model.class);
    }

    public boolean hasIsDomainOf() {
	   return !getIsDomainOf().isEmpty();
    }

    public void addIsDomainOf(Mathematical_Model newIsDomainOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISDOMAINOF,
                                       newIsDomainOf);
    }

    public void removeIsDomainOf(Mathematical_Model oldIsDomainOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISDOMAINOF,
                                          oldIsDomainOf);
    }


}
