package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPrimarySource <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */
public class DefaultPrimarySource extends WrappedIndividualImpl implements PrimarySource {

    public DefaultPrimarySource(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#entity
     */
     
    public Collection<? extends Entity> getEntity() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ENTITY,
                                               DefaultEntity.class);
    }

    public boolean hasEntity() {
	   return !getEntity().isEmpty();
    }

    public void addEntity(Entity newEntity) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ENTITY,
                                       newEntity);
    }

    public void removeEntity(Entity oldEntity) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ENTITY,
                                          oldEntity);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#hadActivity
     */
     
    public Collection<? extends Activity> getHadActivity() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HADACTIVITY,
                                               DefaultActivity.class);
    }

    public boolean hasHadActivity() {
	   return !getHadActivity().isEmpty();
    }

    public void addHadActivity(Activity newHadActivity) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HADACTIVITY,
                                       newHadActivity);
    }

    public void removeHadActivity(Activity oldHadActivity) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HADACTIVITY,
                                          oldHadActivity);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#hadGeneration
     */
     
    public Collection<? extends Generation> getHadGeneration() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HADGENERATION,
                                               DefaultGeneration.class);
    }

    public boolean hasHadGeneration() {
	   return !getHadGeneration().isEmpty();
    }

    public void addHadGeneration(Generation newHadGeneration) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HADGENERATION,
                                       newHadGeneration);
    }

    public void removeHadGeneration(Generation oldHadGeneration) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HADGENERATION,
                                          oldHadGeneration);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#hadRole
     */
     
    public Collection<? extends Role> getHadRole() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HADROLE,
                                               DefaultRole.class);
    }

    public boolean hasHadRole() {
	   return !getHadRole().isEmpty();
    }

    public void addHadRole(Role newHadRole) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HADROLE,
                                       newHadRole);
    }

    public void removeHadRole(Role oldHadRole) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HADROLE,
                                          oldHadRole);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#hadUsage
     */
     
    public Collection<? extends Usage> getHadUsage() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HADUSAGE,
                                               DefaultUsage.class);
    }

    public boolean hasHadUsage() {
	   return !getHadUsage().isEmpty();
    }

    public void addHadUsage(Usage newHadUsage) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HADUSAGE,
                                       newHadUsage);
    }

    public void removeHadUsage(Usage oldHadUsage) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HADUSAGE,
                                          oldHadUsage);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#influencer
     */
     
    public Collection<? extends WrappedIndividual> getInfluencer() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INFLUENCER,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasInfluencer() {
	   return !getInfluencer().isEmpty();
    }

    public void addInfluencer(WrappedIndividual newInfluencer) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INFLUENCER,
                                       newInfluencer);
    }

    public void removeInfluencer(WrappedIndividual oldInfluencer) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INFLUENCER,
                                          oldInfluencer);
    }


}
