package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultUNVBlock <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */
public class DefaultUNVBlock extends WrappedIndividualImpl implements UNVBlock {

    public DefaultUNVBlock(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUNVBlockSettings
     */
     
    public Collection<? extends UNVBlockSettings> getHasUNVBlockSettings() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASUNVBLOCKSETTINGS,
                                               DefaultUNVBlockSettings.class);
    }

    public boolean hasHasUNVBlockSettings() {
	   return !getHasUNVBlockSettings().isEmpty();
    }

    public void addHasUNVBlockSettings(UNVBlockSettings newHasUNVBlockSettings) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASUNVBLOCKSETTINGS,
                                       newHasUNVBlockSettings);
    }

    public void removeHasUNVBlockSettings(UNVBlockSettings oldHasUNVBlockSettings) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASUNVBLOCKSETTINGS,
                                          oldHasUNVBlockSettings);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#isUNVBlockOf
     */
     
    public Collection<? extends UNVOutputFile> getIsUNVBlockOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISUNVBLOCKOF,
                                               DefaultUNVOutputFile.class);
    }

    public boolean hasIsUNVBlockOf() {
	   return !getIsUNVBlockOf().isEmpty();
    }

    public void addIsUNVBlockOf(UNVOutputFile newIsUNVBlockOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISUNVBLOCKOF,
                                       newIsUNVBlockOf);
    }

    public void removeIsUNVBlockOf(UNVOutputFile oldIsUNVBlockOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISUNVBLOCKOF,
                                          oldIsUNVBlockOf);
    }


}
