package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultInitial_Condition <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */
public class DefaultInitial_Condition extends WrappedIndividualImpl implements Initial_Condition {

    public DefaultInitial_Condition(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#isInitialConditionOf
     */
     
    public Collection<? extends Solver> getIsInitialConditionOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISINITIALCONDITIONOF,
                                               DefaultSolver.class);
    }

    public boolean hasIsInitialConditionOf() {
	   return !getIsInitialConditionOf().isEmpty();
    }

    public void addIsInitialConditionOf(Solver newIsInitialConditionOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISINITIALCONDITIONOF,
                                       newIsInitialConditionOf);
    }

    public void removeIsInitialConditionOf(Solver oldIsInitialConditionOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISINITIALCONDITIONOF,
                                          oldIsInitialConditionOf);
    }


}
