package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultElementGroupSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */
public class DefaultElementGroupSettings extends WrappedIndividualImpl implements ElementGroupSettings {

    public DefaultElementGroupSettings(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areElementGroupSettingsOf
     */
     
    public Collection<? extends Elemenmt_Group> getAreElementGroupSettingsOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AREELEMENTGROUPSETTINGSOF,
                                               DefaultElemenmt_Group.class);
    }

    public boolean hasAreElementGroupSettingsOf() {
	   return !getAreElementGroupSettingsOf().isEmpty();
    }

    public void addAreElementGroupSettingsOf(Elemenmt_Group newAreElementGroupSettingsOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AREELEMENTGROUPSETTINGSOF,
                                       newAreElementGroupSettingsOf);
    }

    public void removeAreElementGroupSettingsOf(Elemenmt_Group oldAreElementGroupSettingsOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AREELEMENTGROUPSETTINGSOF,
                                          oldAreElementGroupSettingsOf);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#IATYP
     */
     
    public Collection<? extends Integer> getIATYP() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IATYP, Integer.class);
    }

    public boolean hasIATYP() {
		return !getIATYP().isEmpty();
    }

    public void addIATYP(Integer newIATYP) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IATYP, newIATYP);
    }

    public void removeIATYP(Integer oldIATYP) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IATYP, oldIATYP);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#INDAX
     */
     
    public Collection<? extends Integer> getINDAX() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDAX, Integer.class);
    }

    public boolean hasINDAX() {
		return !getINDAX().isEmpty();
    }

    public void addINDAX(Integer newINDAX) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDAX, newINDAX);
    }

    public void removeINDAX(Integer oldINDAX) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDAX, oldINDAX);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#IPN
     */
     
    public Collection<? extends Integer> getIPN() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IPN, Integer.class);
    }

    public boolean hasIPN() {
		return !getIPN().isEmpty();
    }

    public void addIPN(Integer newIPN) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IPN, newIPN);
    }

    public void removeIPN(Integer oldIPN) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IPN, oldIPN);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#NMODM
     */
     
    public Collection<? extends Integer> getNMODM() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NMODM, Integer.class);
    }

    public boolean hasNMODM() {
		return !getNMODM().isEmpty();
    }

    public void addNMODM(Integer newNMODM) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NMODM, newNMODM);
    }

    public void removeNMODM(Integer oldNMODM) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NMODM, oldNMODM);
    }


}
