package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultSimulation <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */
public class DefaultSimulation extends WrappedIndividualImpl implements Simulation {

    public DefaultSimulation(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasFirstWorkflowStep
     */
     
    public Collection<? extends WrappedIndividual> getHasFirstWorkflowStep() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASFIRSTWORKFLOWSTEP,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasFirstWorkflowStep() {
	   return !getHasFirstWorkflowStep().isEmpty();
    }

    public void addHasFirstWorkflowStep(WrappedIndividual newHasFirstWorkflowStep) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASFIRSTWORKFLOWSTEP,
                                       newHasFirstWorkflowStep);
    }

    public void removeHasFirstWorkflowStep(WrappedIndividual oldHasFirstWorkflowStep) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASFIRSTWORKFLOWSTEP,
                                          oldHasFirstWorkflowStep);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasSimulationComponentFirstWorkflow
     */
     
    public Collection<? extends Activity> getHasSimulationComponentFirstWorkflow() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSIMULATIONCOMPONENTFIRSTWORKFLOW,
                                               DefaultActivity.class);
    }

    public boolean hasHasSimulationComponentFirstWorkflow() {
	   return !getHasSimulationComponentFirstWorkflow().isEmpty();
    }

    public void addHasSimulationComponentFirstWorkflow(Activity newHasSimulationComponentFirstWorkflow) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSIMULATIONCOMPONENTFIRSTWORKFLOW,
                                       newHasSimulationComponentFirstWorkflow);
    }

    public void removeHasSimulationComponentFirstWorkflow(Activity oldHasSimulationComponentFirstWorkflow) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSIMULATIONCOMPONENTFIRSTWORKFLOW,
                                          oldHasSimulationComponentFirstWorkflow);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/Simulation.owl#hasSimulationComponentNextWorkflow
     */
     
    public Collection<? extends Activity> getHasSimulationComponentNextWorkflow() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSIMULATIONCOMPONENTNEXTWORKFLOW,
                                               DefaultActivity.class);
    }

    public boolean hasHasSimulationComponentNextWorkflow() {
	   return !getHasSimulationComponentNextWorkflow().isEmpty();
    }

    public void addHasSimulationComponentNextWorkflow(Activity newHasSimulationComponentNextWorkflow) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSIMULATIONCOMPONENTNEXTWORKFLOW,
                                       newHasSimulationComponentNextWorkflow);
    }

    public void removeHasSimulationComponentNextWorkflow(Activity oldHasSimulationComponentNextWorkflow) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSIMULATIONCOMPONENTNEXTWORKFLOW,
                                          oldHasSimulationComponentNextWorkflow);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#generated
     */
     
    public Collection<? extends Entity> getGenerated() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_GENERATED,
                                               DefaultEntity.class);
    }

    public boolean hasGenerated() {
	   return !getGenerated().isEmpty();
    }

    public void addGenerated(Entity newGenerated) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_GENERATED,
                                       newGenerated);
    }

    public void removeGenerated(Entity oldGenerated) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_GENERATED,
                                          oldGenerated);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#invalidated
     */
     
    public Collection<? extends Entity> getInvalidated() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INVALIDATED,
                                               DefaultEntity.class);
    }

    public boolean hasInvalidated() {
	   return !getInvalidated().isEmpty();
    }

    public void addInvalidated(Entity newInvalidated) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INVALIDATED,
                                       newInvalidated);
    }

    public void removeInvalidated(Entity oldInvalidated) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INVALIDATED,
                                          oldInvalidated);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#qualifiedAssociation
     */
     
    public Collection<? extends Association> getQualifiedAssociation() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_QUALIFIEDASSOCIATION,
                                               DefaultAssociation.class);
    }

    public boolean hasQualifiedAssociation() {
	   return !getQualifiedAssociation().isEmpty();
    }

    public void addQualifiedAssociation(Association newQualifiedAssociation) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_QUALIFIEDASSOCIATION,
                                       newQualifiedAssociation);
    }

    public void removeQualifiedAssociation(Association oldQualifiedAssociation) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_QUALIFIEDASSOCIATION,
                                          oldQualifiedAssociation);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#qualifiedCommunication
     */
     
    public Collection<? extends Communication> getQualifiedCommunication() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_QUALIFIEDCOMMUNICATION,
                                               DefaultCommunication.class);
    }

    public boolean hasQualifiedCommunication() {
	   return !getQualifiedCommunication().isEmpty();
    }

    public void addQualifiedCommunication(Communication newQualifiedCommunication) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_QUALIFIEDCOMMUNICATION,
                                       newQualifiedCommunication);
    }

    public void removeQualifiedCommunication(Communication oldQualifiedCommunication) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_QUALIFIEDCOMMUNICATION,
                                          oldQualifiedCommunication);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#qualifiedEnd
     */
     
    public Collection<? extends End> getQualifiedEnd() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_QUALIFIEDEND,
                                               DefaultEnd.class);
    }

    public boolean hasQualifiedEnd() {
	   return !getQualifiedEnd().isEmpty();
    }

    public void addQualifiedEnd(End newQualifiedEnd) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_QUALIFIEDEND,
                                       newQualifiedEnd);
    }

    public void removeQualifiedEnd(End oldQualifiedEnd) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_QUALIFIEDEND,
                                          oldQualifiedEnd);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#qualifiedStart
     */
     
    public Collection<? extends Start> getQualifiedStart() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_QUALIFIEDSTART,
                                               DefaultStart.class);
    }

    public boolean hasQualifiedStart() {
	   return !getQualifiedStart().isEmpty();
    }

    public void addQualifiedStart(Start newQualifiedStart) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_QUALIFIEDSTART,
                                       newQualifiedStart);
    }

    public void removeQualifiedStart(Start oldQualifiedStart) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_QUALIFIEDSTART,
                                          oldQualifiedStart);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#qualifiedUsage
     */
     
    public Collection<? extends Usage> getQualifiedUsage() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_QUALIFIEDUSAGE,
                                               DefaultUsage.class);
    }

    public boolean hasQualifiedUsage() {
	   return !getQualifiedUsage().isEmpty();
    }

    public void addQualifiedUsage(Usage newQualifiedUsage) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_QUALIFIEDUSAGE,
                                       newQualifiedUsage);
    }

    public void removeQualifiedUsage(Usage oldQualifiedUsage) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_QUALIFIEDUSAGE,
                                          oldQualifiedUsage);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#used
     */
     
    public Collection<? extends Entity> getUsed() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_USED,
                                               DefaultEntity.class);
    }

    public boolean hasUsed() {
	   return !getUsed().isEmpty();
    }

    public void addUsed(Entity newUsed) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_USED,
                                       newUsed);
    }

    public void removeUsed(Entity oldUsed) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_USED,
                                          oldUsed);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#wasAssociatedWith
     */
     
    public Collection<? extends Agent> getWasAssociatedWith() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_WASASSOCIATEDWITH,
                                               DefaultAgent.class);
    }

    public boolean hasWasAssociatedWith() {
	   return !getWasAssociatedWith().isEmpty();
    }

    public void addWasAssociatedWith(Agent newWasAssociatedWith) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_WASASSOCIATEDWITH,
                                       newWasAssociatedWith);
    }

    public void removeWasAssociatedWith(Agent oldWasAssociatedWith) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_WASASSOCIATEDWITH,
                                          oldWasAssociatedWith);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#wasEndedBy
     */
     
    public Collection<? extends Entity> getWasEndedBy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_WASENDEDBY,
                                               DefaultEntity.class);
    }

    public boolean hasWasEndedBy() {
	   return !getWasEndedBy().isEmpty();
    }

    public void addWasEndedBy(Entity newWasEndedBy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_WASENDEDBY,
                                       newWasEndedBy);
    }

    public void removeWasEndedBy(Entity oldWasEndedBy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_WASENDEDBY,
                                          oldWasEndedBy);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#wasInformedBy
     */
     
    public Collection<? extends Activity> getWasInformedBy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_WASINFORMEDBY,
                                               DefaultActivity.class);
    }

    public boolean hasWasInformedBy() {
	   return !getWasInformedBy().isEmpty();
    }

    public void addWasInformedBy(Activity newWasInformedBy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_WASINFORMEDBY,
                                       newWasInformedBy);
    }

    public void removeWasInformedBy(Activity oldWasInformedBy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_WASINFORMEDBY,
                                          oldWasInformedBy);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/ns/prov#wasStartedBy
     */
     
    public Collection<? extends Entity> getWasStartedBy() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_WASSTARTEDBY,
                                               DefaultEntity.class);
    }

    public boolean hasWasStartedBy() {
	   return !getWasStartedBy().isEmpty();
    }

    public void addWasStartedBy(Entity newWasStartedBy) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_WASSTARTEDBY,
                                       newWasStartedBy);
    }

    public void removeWasStartedBy(Entity oldWasStartedBy) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_WASSTARTEDBY,
                                          oldWasStartedBy);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/ns/prov#endedAtTime
     */
     
    public Collection<? extends Object> getEndedAtTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENDEDATTIME, Object.class);
    }

    public boolean hasEndedAtTime() {
		return !getEndedAtTime().isEmpty();
    }

    public void addEndedAtTime(Object newEndedAtTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENDEDATTIME, newEndedAtTime);
    }

    public void removeEndedAtTime(Object oldEndedAtTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENDEDATTIME, oldEndedAtTime);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/ns/prov#startedAtTime
     */
     
    public Collection<? extends Object> getStartedAtTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STARTEDATTIME, Object.class);
    }

    public boolean hasStartedAtTime() {
		return !getStartedAtTime().isEmpty();
    }

    public void addStartedAtTime(Object newStartedAtTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STARTEDATTIME, newStartedAtTime);
    }

    public void removeStartedAtTime(Object oldStartedAtTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_STARTEDATTIME, oldStartedAtTime);
    }


}
