package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMaterialSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */
public class DefaultMaterialSettings extends WrappedIndividualImpl implements MaterialSettings {

    public DefaultMaterialSettings(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areMaterialSettingsOf
     */
     
    public Collection<? extends Material> getAreMaterialSettingsOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AREMATERIALSETTINGSOF,
                                               DefaultMaterial.class);
    }

    public boolean hasAreMaterialSettingsOf() {
	   return !getAreMaterialSettingsOf().isEmpty();
    }

    public void addAreMaterialSettingsOf(Material newAreMaterialSettingsOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AREMATERIALSETTINGSOF,
                                       newAreMaterialSettingsOf);
    }

    public void removeAreMaterialSettingsOf(Material oldAreMaterialSettingsOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AREMATERIALSETTINGSOF,
                                          oldAreMaterialSettingsOf);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#INDJOT
     */
     
    public Collection<? extends Object> getINDJOT() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDJOT, Object.class);
    }

    public boolean hasINDJOT() {
		return !getINDJOT().isEmpty();
    }

    public void addINDJOT(Object newINDJOT) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDJOT, newINDJOT);
    }

    public void removeINDJOT(Object oldINDJOT) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDJOT, oldINDJOT);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#MATTYPE
     */
     
    public Collection<? extends Integer> getMATTYPE() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MATTYPE, Integer.class);
    }

    public boolean hasMATTYPE() {
		return !getMATTYPE().isEmpty();
    }

    public void addMATTYPE(Integer newMATTYPE) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MATTYPE, newMATTYPE);
    }

    public void removeMATTYPE(Integer oldMATTYPE) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MATTYPE, oldMATTYPE);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#model
     */
     
    public Collection<? extends Integer> getModel() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MODEL, Integer.class);
    }

    public boolean hasModel() {
		return !getModel().isEmpty();
    }

    public void addModel(Integer newModel) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MODEL, newModel);
    }

    public void removeModel(Integer oldModel) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MODEL, oldModel);
    }


}
