package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultElementSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */
public class DefaultElementSettings extends WrappedIndividualImpl implements ElementSettings {

    public DefaultElementSettings(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areElementSettingsOf
     */
     
    public Collection<? extends Finite_element> getAreElementSettingsOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AREELEMENTSETTINGSOF,
                                               DefaultFinite_element.class);
    }

    public boolean hasAreElementSettingsOf() {
	   return !getAreElementSettingsOf().isEmpty();
    }

    public void addAreElementSettingsOf(Finite_element newAreElementSettingsOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AREELEMENTSETTINGSOF,
                                       newAreElementSettingsOf);
    }

    public void removeAreElementSettingsOf(Finite_element oldAreElementSettingsOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AREELEMENTSETTINGSOF,
                                          oldAreElementSettingsOf);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedElementBlockValue1
     */
     
    public Collection<? extends Integer> getHasUnusedElementBlockValue1() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE1, Integer.class);
    }

    public boolean hasHasUnusedElementBlockValue1() {
		return !getHasUnusedElementBlockValue1().isEmpty();
    }

    public void addHasUnusedElementBlockValue1(Integer newHasUnusedElementBlockValue1) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE1, newHasUnusedElementBlockValue1);
    }

    public void removeHasUnusedElementBlockValue1(Integer oldHasUnusedElementBlockValue1) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE1, oldHasUnusedElementBlockValue1);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedElementBlockValue2
     */
     
    public Collection<? extends Integer> getHasUnusedElementBlockValue2() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE2, Integer.class);
    }

    public boolean hasHasUnusedElementBlockValue2() {
		return !getHasUnusedElementBlockValue2().isEmpty();
    }

    public void addHasUnusedElementBlockValue2(Integer newHasUnusedElementBlockValue2) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE2, newHasUnusedElementBlockValue2);
    }

    public void removeHasUnusedElementBlockValue2(Integer oldHasUnusedElementBlockValue2) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE2, oldHasUnusedElementBlockValue2);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasUnusedElementBlockValue3
     */
     
    public Collection<? extends Integer> getHasUnusedElementBlockValue3() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE3, Integer.class);
    }

    public boolean hasHasUnusedElementBlockValue3() {
		return !getHasUnusedElementBlockValue3().isEmpty();
    }

    public void addHasUnusedElementBlockValue3(Integer newHasUnusedElementBlockValue3) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE3, newHasUnusedElementBlockValue3);
    }

    public void removeHasUnusedElementBlockValue3(Integer oldHasUnusedElementBlockValue3) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNUSEDELEMENTBLOCKVALUE3, oldHasUnusedElementBlockValue3);
    }


}
