package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultElemenmt_Group <br>
 * @version generated on Mon May 11 16:25:20 BST 2015 by jbjares
 */
public class DefaultElemenmt_Group extends WrappedIndividualImpl implements Elemenmt_Group {

    public DefaultElemenmt_Group(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasElementGroupSetting
     */
     
    public Collection<? extends ElementGroupSettings> getHasElementGroupSetting() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASELEMENTGROUPSETTING,
                                               DefaultElementGroupSettings.class);
    }

    public boolean hasHasElementGroupSetting() {
	   return !getHasElementGroupSetting().isEmpty();
    }

    public void addHasElementGroupSetting(ElementGroupSettings newHasElementGroupSetting) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASELEMENTGROUPSETTING,
                                       newHasElementGroupSetting);
    }

    public void removeHasElementGroupSetting(ElementGroupSettings oldHasElementGroupSetting) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASELEMENTGROUPSETTING,
                                          oldHasElementGroupSetting);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasMaterial
     */
     
    public Collection<? extends Material> getHasMaterial() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASMATERIAL,
                                               DefaultMaterial.class);
    }

    public boolean hasHasMaterial() {
	   return !getHasMaterial().isEmpty();
    }

    public void addHasMaterial(Material newHasMaterial) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASMATERIAL,
                                       newHasMaterial);
    }

    public void removeHasMaterial(Material oldHasMaterial) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASMATERIAL,
                                          oldHasMaterial);
    }


    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasVertex
     */
     
    public Collection<? extends Node> getHasVertex() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASVERTEX,
                                               DefaultNode.class);
    }

    public boolean hasHasVertex() {
	   return !getHasVertex().isEmpty();
    }

    public void addHasVertex(Node newHasVertex) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASVERTEX,
                                       newHasVertex);
    }

    public void removeHasVertex(Node oldHasVertex) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASVERTEX,
                                          oldHasVertex);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FiniteElementModel.owl#hasSpatialDimension
     */
     
    public Collection<? extends Integer> getHasSpatialDimension() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSPATIALDIMENSION, Integer.class);
    }

    public boolean hasHasSpatialDimension() {
		return !getHasSpatialDimension().isEmpty();
    }

    public void addHasSpatialDimension(Integer newHasSpatialDimension) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSPATIALDIMENSION, newHasSpatialDimension);
    }

    public void removeHasSpatialDimension(Integer oldHasSpatialDimension) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSPATIALDIMENSION, oldHasSpatialDimension);
    }


}
