package eu.sifem.model.owl.impl;

import eu.sifem.model.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultFiniteElementModelSettings <br>
 * @version generated on Mon May 11 16:25:19 BST 2015 by jbjares
 */
public class DefaultFiniteElementModelSettings extends WrappedIndividualImpl implements FiniteElementModelSettings {

    public DefaultFiniteElementModelSettings(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#areFiniteElementModelSettingsOf
     */
     
    public Collection<? extends Finite_Element_Model> getAreFiniteElementModelSettingsOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AREFINITEELEMENTMODELSETTINGSOF,
                                               DefaultFinite_Element_Model.class);
    }

    public boolean hasAreFiniteElementModelSettingsOf() {
	   return !getAreFiniteElementModelSettingsOf().isEmpty();
    }

    public void addAreFiniteElementModelSettingsOf(Finite_Element_Model newAreFiniteElementModelSettingsOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AREFINITEELEMENTMODELSETTINGSOF,
                                       newAreFiniteElementModelSettingsOf);
    }

    public void removeAreFiniteElementModelSettingsOf(Finite_Element_Model oldAreFiniteElementModelSettingsOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AREFINITEELEMENTMODELSETTINGSOF,
                                          oldAreFiniteElementModelSettingsOf);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#INDFOR
     */
     
    public Collection<? extends Integer> getINDFOR() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDFOR, Integer.class);
    }

    public boolean hasINDFOR() {
		return !getINDFOR().isEmpty();
    }

    public void addINDFOR(Integer newINDFOR) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDFOR, newINDFOR);
    }

    public void removeINDFOR(Integer oldINDFOR) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INDFOR, oldINDFOR);
    }


    /* ***************************************************
     * Data Property http://www.sifemontologies.com/ontologies/FEMSettingsPAK.owl#hasHeading
     */
     
    public Collection<? extends String> getHasHeading() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHEADING, String.class);
    }

    public boolean hasHasHeading() {
		return !getHasHeading().isEmpty();
    }

    public void addHasHeading(String newHasHeading) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHEADING, newHasHeading);
    }

    public void removeHasHeading(String oldHasHeading) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHEADING, oldHasHeading);
    }


}
